services:
  backend:
    container_name: ${CONTAINER_NAME_BACKEND:-cinemaub-prod-backend}
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      # Assegura que Django veu host i CSRF des del .env
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE:-cinemaub.settings}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG:-False}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    volumes:
      - ./backend/media:/app/media
      - ./backend/db.sqlite3:/app/db.sqlite3
    expose:
      - "8000"
    networks:
      web:
        aliases:
          # Alias ÚNIC per aquest stack
          - ${CONTAINER_NAME_BACKEND:-cinemaub-prod-backend}
    restart: unless-stopped

networks:
  web:
    external: true