services:
  frontend:
    container_name: ${CONTAINER_NAME_FRONTEND:-cinemaub-prod-frontend}
    build:
      context: ./app-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/}
    env_file:
      - .env
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/}
    expose:
      - "80"
    networks:
      web:
        aliases:
          # Alias ÚNIC per aquest stack
          - ${CONTAINER_NAME_FRONTEND:-cinemaub-prod-frontend}
    restart: unless-stopped

networks:
  web:
    external: true
