# Generated by Django 5.2.7 on 2025-10-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="release_year",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="synopsis",
        ),
        migrations.AddField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="num_votes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="movie",
            name="poster_attribution",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="poster_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="primary_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="start_year",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="tconst",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
