# Generated by Django 5.2.7 on 2025-10-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_remove_movie_release_year_remove_movie_synopsis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="imdb_rating",
            field=models.FloatField(default=0.0),
        ),
    ]
