# Generated by Django 5.2.7 on 2025-10-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_movie_imdb_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
