# Generated by Django 5.2.7 on 2025-10-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_movie_actors_movie_genres"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="num_votes",
        ),
    ]
