# Generated by assistant: add date field to Rating
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
