# Generated by assistant: populate existing rating.date and make field non-nullable
from django.db import migrations, models
import django.utils.timezone


def set_rating_dates(apps, schema_editor):
    Rating = apps.get_model('movies', 'Rating')
    now = django.utils.timezone.now()
    # Set current time for any existing null date values
    Rating.objects.filter(date__isnull=True).update(date=now)


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_add_rating_date'),
    ]

    operations = [
        migrations.RunPython(set_rating_dates, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
