# Generated by Django 5.2 on 2025-11-28 09:50

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_populate_and_make_rating_date_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=movies.models.avatar_upload_path),
        ),
    ]
