# Generated by Django 5.2 on 2025-11-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_migrate_comments_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='comment',
        ),
    ]
