# Generated by Django 5.2 on 2025-11-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_comment_unique_together_comment_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
