# Generated by Django 5.2 on 2025-12-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0019_forum_forumpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
